package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/vladimirdotk/news-bot/internal/domain"
)

// ResponseSenderMock implements command.ResponseSender
type ResponseSenderMock struct {
	t minimock.Tester

	funcSend          func(message domain.OutgoingMessage) (err error)
	inspectFuncSend   func(message domain.OutgoingMessage)
	afterSendCounter  uint64
	beforeSendCounter uint64
	SendMock          mResponseSenderMockSend
}

// NewResponseSenderMock returns a mock for command.ResponseSender
func NewResponseSenderMock(t minimock.Tester) *ResponseSenderMock {
	m := &ResponseSenderMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SendMock = mResponseSenderMockSend{mock: m}
	m.SendMock.callArgs = []*ResponseSenderMockSendParams{}

	return m
}

type mResponseSenderMockSend struct {
	mock               *ResponseSenderMock
	defaultExpectation *ResponseSenderMockSendExpectation
	expectations       []*ResponseSenderMockSendExpectation

	callArgs []*ResponseSenderMockSendParams
	mutex    sync.RWMutex
}

// ResponseSenderMockSendExpectation specifies expectation struct of the ResponseSender.Send
type ResponseSenderMockSendExpectation struct {
	mock    *ResponseSenderMock
	params  *ResponseSenderMockSendParams
	results *ResponseSenderMockSendResults
	Counter uint64
}

// ResponseSenderMockSendParams contains parameters of the ResponseSender.Send
type ResponseSenderMockSendParams struct {
	message domain.OutgoingMessage
}

// ResponseSenderMockSendResults contains results of the ResponseSender.Send
type ResponseSenderMockSendResults struct {
	err error
}

// Expect sets up expected params for ResponseSender.Send
func (mmSend *mResponseSenderMockSend) Expect(message domain.OutgoingMessage) *mResponseSenderMockSend {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("ResponseSenderMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &ResponseSenderMockSendExpectation{}
	}

	mmSend.defaultExpectation.params = &ResponseSenderMockSendParams{message}
	for _, e := range mmSend.expectations {
		if minimock.Equal(e.params, mmSend.defaultExpectation.params) {
			mmSend.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSend.defaultExpectation.params)
		}
	}

	return mmSend
}

// Inspect accepts an inspector function that has same arguments as the ResponseSender.Send
func (mmSend *mResponseSenderMockSend) Inspect(f func(message domain.OutgoingMessage)) *mResponseSenderMockSend {
	if mmSend.mock.inspectFuncSend != nil {
		mmSend.mock.t.Fatalf("Inspect function is already set for ResponseSenderMock.Send")
	}

	mmSend.mock.inspectFuncSend = f

	return mmSend
}

// Return sets up results that will be returned by ResponseSender.Send
func (mmSend *mResponseSenderMockSend) Return(err error) *ResponseSenderMock {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("ResponseSenderMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &ResponseSenderMockSendExpectation{mock: mmSend.mock}
	}
	mmSend.defaultExpectation.results = &ResponseSenderMockSendResults{err}
	return mmSend.mock
}

//Set uses given function f to mock the ResponseSender.Send method
func (mmSend *mResponseSenderMockSend) Set(f func(message domain.OutgoingMessage) (err error)) *ResponseSenderMock {
	if mmSend.defaultExpectation != nil {
		mmSend.mock.t.Fatalf("Default expectation is already set for the ResponseSender.Send method")
	}

	if len(mmSend.expectations) > 0 {
		mmSend.mock.t.Fatalf("Some expectations are already set for the ResponseSender.Send method")
	}

	mmSend.mock.funcSend = f
	return mmSend.mock
}

// When sets expectation for the ResponseSender.Send which will trigger the result defined by the following
// Then helper
func (mmSend *mResponseSenderMockSend) When(message domain.OutgoingMessage) *ResponseSenderMockSendExpectation {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("ResponseSenderMock.Send mock is already set by Set")
	}

	expectation := &ResponseSenderMockSendExpectation{
		mock:   mmSend.mock,
		params: &ResponseSenderMockSendParams{message},
	}
	mmSend.expectations = append(mmSend.expectations, expectation)
	return expectation
}

// Then sets up ResponseSender.Send return parameters for the expectation previously defined by the When method
func (e *ResponseSenderMockSendExpectation) Then(err error) *ResponseSenderMock {
	e.results = &ResponseSenderMockSendResults{err}
	return e.mock
}

// Send implements command.ResponseSender
func (mmSend *ResponseSenderMock) Send(message domain.OutgoingMessage) (err error) {
	mm_atomic.AddUint64(&mmSend.beforeSendCounter, 1)
	defer mm_atomic.AddUint64(&mmSend.afterSendCounter, 1)

	if mmSend.inspectFuncSend != nil {
		mmSend.inspectFuncSend(message)
	}

	mm_params := &ResponseSenderMockSendParams{message}

	// Record call args
	mmSend.SendMock.mutex.Lock()
	mmSend.SendMock.callArgs = append(mmSend.SendMock.callArgs, mm_params)
	mmSend.SendMock.mutex.Unlock()

	for _, e := range mmSend.SendMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSend.SendMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSend.SendMock.defaultExpectation.Counter, 1)
		mm_want := mmSend.SendMock.defaultExpectation.params
		mm_got := ResponseSenderMockSendParams{message}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSend.t.Errorf("ResponseSenderMock.Send got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSend.SendMock.defaultExpectation.results
		if mm_results == nil {
			mmSend.t.Fatal("No results are set for the ResponseSenderMock.Send")
		}
		return (*mm_results).err
	}
	if mmSend.funcSend != nil {
		return mmSend.funcSend(message)
	}
	mmSend.t.Fatalf("Unexpected call to ResponseSenderMock.Send. %v", message)
	return
}

// SendAfterCounter returns a count of finished ResponseSenderMock.Send invocations
func (mmSend *ResponseSenderMock) SendAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSend.afterSendCounter)
}

// SendBeforeCounter returns a count of ResponseSenderMock.Send invocations
func (mmSend *ResponseSenderMock) SendBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSend.beforeSendCounter)
}

// Calls returns a list of arguments used in each call to ResponseSenderMock.Send.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSend *mResponseSenderMockSend) Calls() []*ResponseSenderMockSendParams {
	mmSend.mutex.RLock()

	argCopy := make([]*ResponseSenderMockSendParams, len(mmSend.callArgs))
	copy(argCopy, mmSend.callArgs)

	mmSend.mutex.RUnlock()

	return argCopy
}

// MinimockSendDone returns true if the count of the Send invocations corresponds
// the number of defined expectations
func (m *ResponseSenderMock) MinimockSendDone() bool {
	for _, e := range m.SendMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SendMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSendCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSend != nil && mm_atomic.LoadUint64(&m.afterSendCounter) < 1 {
		return false
	}
	return true
}

// MinimockSendInspect logs each unmet expectation
func (m *ResponseSenderMock) MinimockSendInspect() {
	for _, e := range m.SendMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ResponseSenderMock.Send with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SendMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSendCounter) < 1 {
		if m.SendMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to ResponseSenderMock.Send")
		} else {
			m.t.Errorf("Expected call to ResponseSenderMock.Send with params: %#v", *m.SendMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSend != nil && mm_atomic.LoadUint64(&m.afterSendCounter) < 1 {
		m.t.Error("Expected call to ResponseSenderMock.Send")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ResponseSenderMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockSendInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ResponseSenderMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ResponseSenderMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSendDone()
}
